// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaomKBUfaEylecfMzz6mGEOCFZx-s6vZ0',
    appId: '1:3207173302:web:480137dee12ff68c70c217',
    messagingSenderId: '3207173302',
    projectId: 'innodify-db-firebase',
    authDomain: 'innodify-db-firebase.firebaseapp.com',
    storageBucket: 'innodify-db-firebase.appspot.com',
    measurementId: 'G-FVERKBHFM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVzhuk6v_Dn4RHF4bVXG9halWNqII35t0',
    appId: '1:3207173302:android:81a26a457c4b7c0570c217',
    messagingSenderId: '3207173302',
    projectId: 'innodify-db-firebase',
    storageBucket: 'innodify-db-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_uZ2xPopAP-HltTdoCZNYsMPsYW54fzk',
    appId: '1:3207173302:ios:53a2229c642b23ca70c217',
    messagingSenderId: '3207173302',
    projectId: 'innodify-db-firebase',
    storageBucket: 'innodify-db-firebase.appspot.com',
    iosBundleId: 'com.innodify.vendor.innodifyVendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_uZ2xPopAP-HltTdoCZNYsMPsYW54fzk',
    appId: '1:3207173302:ios:53a2229c642b23ca70c217',
    messagingSenderId: '3207173302',
    projectId: 'innodify-db-firebase',
    storageBucket: 'innodify-db-firebase.appspot.com',
    iosBundleId: 'com.innodify.vendor.innodifyVendorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaomKBUfaEylecfMzz6mGEOCFZx-s6vZ0',
    appId: '1:3207173302:web:7fae73516c4d1a3070c217',
    messagingSenderId: '3207173302',
    projectId: 'innodify-db-firebase',
    authDomain: 'innodify-db-firebase.firebaseapp.com',
    storageBucket: 'innodify-db-firebase.appspot.com',
    measurementId: 'G-2VP24P6JD1',
  );
}
